name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: fedora:41

    steps:
    - uses: actions/checkout@v4
    - name: deps
      run: sudo dnf -y update && sudo dnf -y install make diff gcc readline-devel
    - name: make
      run: make
    - name: make test
      run: make test
